# Generated by Django 5.2.8 on 2026-01-14 16:32

import attendences.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(validators=[attendences.models.validate_attendance_date]),
        ),
    ]
