# Generated by Django 5.2.8 on 2026-01-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_options_alter_course_credits_and_more'),
        ('emrollments', '0001_initial'),
        ('students', '0002_alter_student_date_of_birth_alter_student_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-enrollment_date']},
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('Enrolled', 'Enrolled'), ('Completed', 'Completed'), ('Dropped', 'Dropped')], default='Enrolled', max_length=15),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='unique_student_course_enrollment'),
        ),
    ]
