# Generated by Django 5.2.8 on 2026-01-14 09:23

import django.core.validators
import students.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(validators=[students.validators.validate_date_of_birth]),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Phone must contain only numbers and can start with + (8-20 digits).', regex='^\\+?\\d{8,20}$')]),
        ),
    ]
